Job submission scripts adjustments. Less abtrusive.

diff --git a/M b/M
--- a/M
+++ b/M
@@ -1,5 +1,22 @@
 #!/usr/bin/env bash
 
+while getopts ":j" opt; do
+    case $opt in
+    j)
+        jobfile=$OPTARG
+        ;;
+    \?)
+        echo "Invalid option: -$OPTARG" >&2
+        exit 1
+        ;;
+    :)
+        echo "Option -$OPTARG requires an argument." >&2
+        exit 1
+        ;;
+  esac
+done
+
+shift $(($OPTIND-1))
 directory_name="$1"
 
 if [[ -d "$directory_name" && $(ls -A "$directory_name") ]]; then
@@ -11,4 +28,8 @@ else
     exit 1
 fi
 
-qsub qsub.parallel
+if [[ -z $jobfile ]]; then
+    qsub qsub.parallel
+else
+    qsub $jobfile
+fi
